### PR TITLE
proposal to add windows support to the custom target functionality

### PR DESCRIPTION
**Pull request by Brookke**

### CODE REVIEW

**Comment by MarvinJWendt** [comment]
Hi  @Brookke, I can't get this to run:

image

**Comment by Brookke** [comment]
@MarvinJWendt I have made some changes, could you also share your "experimenting" code if you don't mind and I can test my side :)

**Comment by MarvinJWendt** [comment]
Hi @Brookke, the experimenting code is actually not relevant. It was a simple hello world, but the code didn't compile 😅

**Comment by Brookke** [comment]
> Hi @Brookke, the experimenting code is actually not relevant. It was a simple hello world, but the code didn't compile 😅

Hopefully the code should compile now. I have done some testing on a windows vm and it seems to work. The test will fail as the underlying calls are different on windows.

**Comment by MarvinJWendt** [comment]
Hi @Brookke, sorry for the long wait. I am currently looking into fixing the tests :)

**Review by MarvinJWendt — APPROVED** [review]
LGTM! Thanks for the PR :)

**Pull request merged**
